# Makefile created by Yuanxin Pan (yxpan@whu.edu.cn), on Jun 1, 2019

all : xyz2enu

CC = g++
CPPFALGS = -Wall -O3

xyz2enu : xyz2enu.cpp
	$(CC) $(CPPFALGS) $< -o $@

.PHONY : clean
clean :
	-rm xyz2enu

